// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreatePetData,
  CreatePetResponse,
  DeletePetData,
  DeletePetResponse,
  GetInventoryResponse,
  ListPetsData,
  ListPetsResponse,
  ShowPetByIdData,
  ShowPetByIdResponse,
  UpdatePetData,
  UpdatePetResponse,
} from './types.gen';

export type PetsControllerMethods = {
  listPets: (query?: ListPetsData['query']) => Promise<ListPetsResponse>;
  createPet: (body: CreatePetData['body']) => Promise<CreatePetResponse>;
  deletePet: (path: DeletePetData['path']) => Promise<DeletePetResponse>;
  showPetById: (path: ShowPetByIdData['path']) => Promise<ShowPetByIdResponse>;
  updatePet: (
    path: UpdatePetData['path'],
    body: UpdatePetData['body'],
  ) => Promise<UpdatePetResponse>;
};

export type StoreControllerMethods = {
  getInventory: () => Promise<GetInventoryResponse>;
};
