// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Config, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CallToTestOrderOfParamsData, CallWithDefaultOptionalParametersData, CallWithDefaultParametersData, CallWithDescriptionsData, CallWithDuplicateResponsesData, CallWithDuplicateResponsesErrors, CallWithDuplicateResponsesResponses, CallWithNoContentResponseData, CallWithNoContentResponseResponses, CallWithParametersData, CallWithResponseAndNoContentResponseData, CallWithResponseAndNoContentResponseResponses, CallWithResponseData, CallWithResponseResponses, CallWithResponsesData, CallWithResponsesErrors, CallWithResponsesResponses, CallWithResultFromHeaderData, CallWithResultFromHeaderErrors, CallWithResultFromHeaderResponses, CallWithWeirdParameterNamesData, CollectionFormatData, ComplexTypesData, ComplexTypesErrors, ComplexTypesResponses, DeleteCallWithoutParametersAndResponseData, DummyAData, DummyAResponses, DummyBData, DummyBResponses, DuplicateName2Data, DuplicateName3Data, DuplicateName4Data, DuplicateNameData, FooWowData, FooWowResponses, GetCallWithoutParametersAndResponseData, HeadCallWithoutParametersAndResponseData, NonAsciiæøåÆøÅöôêÊ字符串Data, NonAsciiæøåÆøÅöôêÊ字符串Responses, OptionsCallWithoutParametersAndResponseData, PatchApiVbyApiVersionNoTagData, PatchApiVbyApiVersionNoTagResponses, PatchCallWithoutParametersAndResponseData, PostApiVbyApiVersionBodyData, PostApiVbyApiVersionBodyErrors, PostApiVbyApiVersionBodyResponses, PostCallWithoutParametersAndResponseData, PutCallWithoutParametersAndResponseData, ServiceWithEmptyTagData, TestErrorCodeData, TestErrorCodeErrors, TestErrorCodeResponses, TypesData, TypesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown, TParseAs extends NonNullable<Config['parseAs']> = 'auto'> = Options2<TData, ThrowOnError, TResponse, 'fields', TParseAs> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const serviceWithEmptyTag = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<ServiceWithEmptyTagData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/no+tag', ...options });

export const patchApiVbyApiVersionNoTag = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<PatchApiVbyApiVersionNoTagData, ThrowOnError, PatchApiVbyApiVersionNoTagResponses, TParseAs>): RequestResult<PatchApiVbyApiVersionNoTagResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).patch<PatchApiVbyApiVersionNoTagResponses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/no+tag', ...options });

export const fooWow = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<FooWowData, ThrowOnError, FooWowResponses, TParseAs>): RequestResult<FooWowResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).put<FooWowResponses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/no+tag', ...options });

export const deleteCallWithoutParametersAndResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<DeleteCallWithoutParametersAndResponseData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).delete<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/simple', ...options });

export const getCallWithoutParametersAndResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<GetCallWithoutParametersAndResponseData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/simple', ...options });

export const headCallWithoutParametersAndResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<HeadCallWithoutParametersAndResponseData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).head<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/simple', ...options });

export const optionsCallWithoutParametersAndResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<OptionsCallWithoutParametersAndResponseData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).options<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/simple', ...options });

export const patchCallWithoutParametersAndResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<PatchCallWithoutParametersAndResponseData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).patch<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/simple', ...options });

export const postCallWithoutParametersAndResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<PostCallWithoutParametersAndResponseData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).post<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/simple', ...options });

export const putCallWithoutParametersAndResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<PutCallWithoutParametersAndResponseData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).put<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/simple', ...options });

export const callWithDescriptions = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithDescriptionsData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).post<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/descriptions/', ...options });

export const callWithParameters = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<CallWithParametersData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).post<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/parameters/{parameterPath}', ...options });

export const callWithWeirdParameterNames = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<CallWithWeirdParameterNamesData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).post<unknown, unknown, ThrowOnError, 'fields', TParseAs>({
    url: '/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const callWithDefaultParameters = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<CallWithDefaultParametersData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).get<unknown, unknown, ThrowOnError, 'fields', TParseAs>({
    querySerializer: { parameters: { parameterModel: { object: { explode: false, style: 'form' } } } },
    url: '/api/v{api-version}/defaults',
    ...options
});

export const callWithDefaultOptionalParameters = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithDefaultOptionalParametersData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).post<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/defaults', ...options });

export const callToTestOrderOfParams = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<CallToTestOrderOfParamsData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).put<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/defaults', ...options });

export const duplicateName = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<DuplicateNameData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).delete<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/duplicate', ...options });

export const duplicateName2 = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<DuplicateName2Data, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/duplicate', ...options });

export const duplicateName3 = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<DuplicateName3Data, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).post<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/duplicate', ...options });

export const duplicateName4 = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<DuplicateName4Data, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).put<unknown, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/duplicate', ...options });

export const callWithNoContentResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithNoContentResponseData, ThrowOnError, CallWithNoContentResponseResponses, TParseAs>): RequestResult<CallWithNoContentResponseResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<CallWithNoContentResponseResponses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/no-content', ...options });

export const callWithResponseAndNoContentResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithResponseAndNoContentResponseData, ThrowOnError, CallWithResponseAndNoContentResponseResponses, TParseAs>): RequestResult<CallWithResponseAndNoContentResponseResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<CallWithResponseAndNoContentResponseResponses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/multiple-tags/response-and-no-content', ...options });

export const dummyA = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<DummyAData, ThrowOnError, DummyAResponses, TParseAs>): RequestResult<DummyAResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<DummyAResponses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/multiple-tags/a', ...options });

export const dummyB = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<DummyBData, ThrowOnError, DummyBResponses, TParseAs>): RequestResult<DummyBResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<DummyBResponses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/multiple-tags/b', ...options });

export const callWithResponse = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithResponseData, ThrowOnError, CallWithResponseResponses, TParseAs>): RequestResult<CallWithResponseResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).get<CallWithResponseResponses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/response', ...options });

export const callWithDuplicateResponses = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithDuplicateResponsesData, ThrowOnError, CallWithDuplicateResponsesResponses, TParseAs>): RequestResult<CallWithDuplicateResponsesResponses, CallWithDuplicateResponsesErrors, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).post<CallWithDuplicateResponsesResponses, CallWithDuplicateResponsesErrors, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/response', ...options });

export const callWithResponses = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithResponsesData, ThrowOnError, CallWithResponsesResponses, TParseAs>): RequestResult<CallWithResponsesResponses, CallWithResponsesErrors, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).put<CallWithResponsesResponses, CallWithResponsesErrors, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/response', ...options });

export const collectionFormat = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<CollectionFormatData, ThrowOnError, unknown, TParseAs>): RequestResult<unknown, unknown, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).get<unknown, unknown, ThrowOnError, 'fields', TParseAs>({
    querySerializer: { parameters: {
            parameterArrayCSV: { array: { explode: false } },
            parameterArraySSV: { array: { explode: false } },
            parameterArrayTSV: { array: { explode: false } },
            parameterArrayPipes: { array: { explode: false } }
        } },
    url: '/api/v{api-version}/collectionFormat',
    ...options
});

export const types = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<TypesData, ThrowOnError, TypesResponses, TParseAs>): RequestResult<TypesResponses, unknown, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).get<TypesResponses, unknown, ThrowOnError, 'fields', TParseAs>({
    querySerializer: { parameters: { parameterArray: { array: { explode: false } }, parameterDictionary: { object: { explode: false, style: 'form' } } } },
    url: '/api/v{api-version}/types',
    ...options
});

export const complexTypes = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<ComplexTypesData, ThrowOnError, ComplexTypesResponses, TParseAs>): RequestResult<ComplexTypesResponses, ComplexTypesErrors, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).get<ComplexTypesResponses, ComplexTypesErrors, ThrowOnError, 'fields', TParseAs>({
    querySerializer: { parameters: { parameterObject: { object: { explode: false, style: 'form' } }, parameterReference: { object: { explode: false, style: 'form' } } } },
    url: '/api/v{api-version}/complex',
    ...options
});

export const callWithResultFromHeader = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options?: Options<CallWithResultFromHeaderData, ThrowOnError, CallWithResultFromHeaderResponses, TParseAs>): RequestResult<CallWithResultFromHeaderResponses, CallWithResultFromHeaderErrors, ThrowOnError, 'fields', TParseAs> => (options?.client ?? client).post<CallWithResultFromHeaderResponses, CallWithResultFromHeaderErrors, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/header', ...options });

export const testErrorCode = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<TestErrorCodeData, ThrowOnError, TestErrorCodeResponses, TParseAs>): RequestResult<TestErrorCodeResponses, TestErrorCodeErrors, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).post<TestErrorCodeResponses, TestErrorCodeErrors, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/error', ...options });

export const nonAsciiæøåÆøÅöôêÊ字符串 = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<NonAsciiæøåÆøÅöôêÊ字符串Data, ThrowOnError, NonAsciiæøåÆøÅöôêÊ字符串Responses, TParseAs>): RequestResult<NonAsciiæøåÆøÅöôêÊ字符串Responses, unknown, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).post<NonAsciiæøåÆøÅöôêÊ字符串Responses, unknown, ThrowOnError, 'fields', TParseAs>({ url: '/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串', ...options });

/**
 * Body should not be unknown
 *
 * Body should not be unknown
 */
export const postApiVbyApiVersionBody = <ThrowOnError extends boolean = true, TParseAs extends NonNullable<Config['parseAs']> = 'auto'>(options: Options<PostApiVbyApiVersionBodyData, ThrowOnError, PostApiVbyApiVersionBodyResponses, TParseAs>): RequestResult<PostApiVbyApiVersionBodyResponses, PostApiVbyApiVersionBodyErrors, ThrowOnError, 'fields', TParseAs> => (options.client ?? client).post<PostApiVbyApiVersionBodyResponses, PostApiVbyApiVersionBodyErrors, ThrowOnError, 'fields', TParseAs>({
    url: '/api/v{api-version}/body',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
