// This file is auto-generated by @hey-api/openapi-ts

import { useMutation, type UseMutationOptions } from '@pinia/colada';
import { toRef } from 'vue';
import type { UploadFileResponse, UploadFileData } from '../../types.gen';
import { client } from '@pinia/colada/client';

export const useUploadFileMutation = async (params: {}, options?: UseMutationOptions<UploadFileResponse, UploadFileData, unknown>) => {
    const pathRef = toRef(params?.path);
    const bodyRef = toRef(params?.body);
    const mutation = useMutation({
        mutation: client({
            method: 'post',
            url: '/api/v{api-version}/upload',
            pathRef,
            bodyRef
        }),
        key: [
            'Upload',
            'uploadFile',
            pathRef,
            bodyRef
        ],
        ...options
    });
    return {
        ...mutation,
        path: pathRef,
        body: bodyRef
    };
};