// This file is auto-generated by @hey-api/openapi-ts

import { Module, DynamicModule } from '@nestjs/common';

import type { ClientModuleConfig, ClientModuleAsyncConfig } from './types.gen';

import { CustomClientClient } from './customclient-client.service.gen';

import { CustomClientDefaultService } from './services/customclient-default.service.gen';

import { CustomClientSimpleService } from './services/customclient-simple.service.gen';

import { CustomClientParametersService } from './services/customclient-parameters.service.gen';

import { CustomClientDescriptionsService } from './services/customclient-descriptions.service.gen';

import { CustomClientDeprecatedService } from './services/customclient-deprecated.service.gen';

import { CustomClientRequestBodyService } from './services/customclient-requestbody.service.gen';

import { CustomClientFormDataService } from './services/customclient-formdata.service.gen';

import { CustomClientDefaultsService } from './services/customclient-defaults.service.gen';

import { CustomClientDuplicateService } from './services/customclient-duplicate.service.gen';

import { CustomClientNoContentService } from './services/customclient-nocontent.service.gen';

import { CustomClientResponseService } from './services/customclient-response.service.gen';

import { CustomClientNoContentService } from './services/customclient-nocontent.service.gen';

import { CustomClientMultipleTags1Service } from './services/customclient-multipletags1.service.gen';

import { CustomClientMultipleTags2Service } from './services/customclient-multipletags2.service.gen';

import { CustomClientMultipleTags3Service } from './services/customclient-multipletags3.service.gen';

import { CustomClientCollectionFormatService } from './services/customclient-collectionformat.service.gen';

import { CustomClientTypesService } from './services/customclient-types.service.gen';

import { CustomClientUploadService } from './services/customclient-upload.service.gen';

import { CustomClientFileResponseService } from './services/customclient-fileresponse.service.gen';

import { CustomClientComplexService } from './services/customclient-complex.service.gen';

import { CustomClientMultipartService } from './services/customclient-multipart.service.gen';

import { CustomClientHeaderService } from './services/customclient-header.service.gen';

import { CustomClientErrorService } from './services/customclient-error.service.gen';

import { CustomClientNonAsciiÆøåÆøÅöôêÊService } from './services/customclient-non-ascii-æøåæøåöôêê.service.gen';

@Module({})
export class MyCustomModule {
    public static forRoot(config: ClientModuleConfig): DynamicModule {
        return {
            module: MyCustomModule,
            providers: [
                {
                    provide: 'CUSTOM_CLIENT_CLIENT_CONFIG',
                    useValue: config
                },
                CustomClientClient,
                CustomClientDefaultService,
                CustomClientSimpleService,
                CustomClientParametersService,
                CustomClientDescriptionsService,
                CustomClientDeprecatedService,
                CustomClientRequestBodyService,
                CustomClientFormDataService,
                CustomClientDefaultsService,
                CustomClientDuplicateService,
                CustomClientNoContentService,
                CustomClientResponseService,
                CustomClientNoContentService,
                CustomClientMultipleTags1Service,
                CustomClientMultipleTags2Service,
                CustomClientMultipleTags3Service,
                CustomClientCollectionFormatService,
                CustomClientTypesService,
                CustomClientUploadService,
                CustomClientFileResponseService,
                CustomClientComplexService,
                CustomClientMultipartService,
                CustomClientHeaderService,
                CustomClientErrorService,
                CustomClientNonAsciiÆøåÆøÅöôêÊService
            ],
            exports: [
                CustomClientClient,
                CustomClientDefaultService,
                CustomClientSimpleService,
                CustomClientParametersService,
                CustomClientDescriptionsService,
                CustomClientDeprecatedService,
                CustomClientRequestBodyService,
                CustomClientFormDataService,
                CustomClientDefaultsService,
                CustomClientDuplicateService,
                CustomClientNoContentService,
                CustomClientResponseService,
                CustomClientNoContentService,
                CustomClientMultipleTags1Service,
                CustomClientMultipleTags2Service,
                CustomClientMultipleTags3Service,
                CustomClientCollectionFormatService,
                CustomClientTypesService,
                CustomClientUploadService,
                CustomClientFileResponseService,
                CustomClientComplexService,
                CustomClientMultipartService,
                CustomClientHeaderService,
                CustomClientErrorService,
                CustomClientNonAsciiÆøåÆøÅöôêÊService
            ]
        };
    }
    public static forRootAsync(options: ClientModuleAsyncConfig): DynamicModule {
        return {
            module: MyCustomModule,
            imports: options.imports ? options.imports : [],
            providers: [
                {
                    provide: 'CUSTOM_CLIENT_CLIENT_CONFIG',
                    useFactory: options.useFactory ? options.useFactory : (): ClientModuleConfig => {
                        return {};
                    },
                    inject: options.inject ? options.inject : []
                },
                CustomClientClient,
                CustomClientDefaultService,
                CustomClientSimpleService,
                CustomClientParametersService,
                CustomClientDescriptionsService,
                CustomClientDeprecatedService,
                CustomClientRequestBodyService,
                CustomClientFormDataService,
                CustomClientDefaultsService,
                CustomClientDuplicateService,
                CustomClientNoContentService,
                CustomClientResponseService,
                CustomClientNoContentService,
                CustomClientMultipleTags1Service,
                CustomClientMultipleTags2Service,
                CustomClientMultipleTags3Service,
                CustomClientCollectionFormatService,
                CustomClientTypesService,
                CustomClientUploadService,
                CustomClientFileResponseService,
                CustomClientComplexService,
                CustomClientMultipartService,
                CustomClientHeaderService,
                CustomClientErrorService,
                CustomClientNonAsciiÆøåÆøÅöôêÊService
            ],
            exports: [
                CustomClientClient,
                CustomClientDefaultService,
                CustomClientSimpleService,
                CustomClientParametersService,
                CustomClientDescriptionsService,
                CustomClientDeprecatedService,
                CustomClientRequestBodyService,
                CustomClientFormDataService,
                CustomClientDefaultsService,
                CustomClientDuplicateService,
                CustomClientNoContentService,
                CustomClientResponseService,
                CustomClientNoContentService,
                CustomClientMultipleTags1Service,
                CustomClientMultipleTags2Service,
                CustomClientMultipleTags3Service,
                CustomClientCollectionFormatService,
                CustomClientTypesService,
                CustomClientUploadService,
                CustomClientFileResponseService,
                CustomClientComplexService,
                CustomClientMultipartService,
                CustomClientHeaderService,
                CustomClientErrorService,
                CustomClientNonAsciiÆøåÆøÅöôêÊService
            ]
        };
    }
}