// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type FileUploadRequest = {
    /**
     * Binary file content
     */
    file: Blob | File;
};

export type FileUploadRequestTyped = {
    /**
     * Binary file content with explicit string type
     */
    file: Blob | File;
};

export type UploadFileData = {
    body?: FileUploadRequest;
    path?: never;
    query?: never;
    url: '/upload';
};

export type UploadFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UploadFileTypedData = {
    body?: FileUploadRequestTyped;
    path?: never;
    query?: never;
    url: '/upload-typed';
};

export type UploadFileTypedResponses = {
    /**
     * OK
     */
    200: unknown;
};
