// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod/v3';

export const zBar: z.AnyZodObject = z.object({
    get foo(): z.ZodTypeAny {
        return z.lazy(() => {
            return zFoo;
        }).optional();
    }
});

export const zFoo: z.ZodTypeAny = z.union([
    z.object({
        foo: z.string().regex(/^\d{3}-\d{2}-\d{4}$/).optional(),
        get bar() {
            return zBar.optional();
        },
        get baz(): z.ZodTypeAny {
            return z.array(z.lazy(() => {
                return zFoo;
            })).optional();
        },
        qux: z.number().int().gt(0).optional().default(0)
    }),
    z.null()
]).default(null);

export const zBaz = z.string().regex(/foo\nbar/).readonly().default('baz');
