// This file is auto-generated by @hey-api/openapi-ts

import { Injectable } from '@nestjs/common';

import type { AxiosResponse } from 'axios';

import { CustomClientClient } from '../customclient-client.service.gen';

import type { Options, TDataShape } from '../types.gen';

import type { DummyBData, DummyBResponses } from '../../types.gen';

@Injectable()
export class CustomClientMultipleTags3Service {
    constructor(private readonly client: CustomClientClient) {
    }
    public async dummyB(options: DummyBData): Promise<AxiosResponse<DummyBResponses[200]>> {
        return await this.client.get(options.url, {
            ...options
        });
    }
}