// This file is auto-generated by @hey-api/openapi-ts

import { Injectable } from '@nestjs/common';

import type { AxiosResponse } from 'axios';

import { CustomClientClient } from '../customclient-client.service.gen';

import type { Options, TDataShape } from '../types.gen';

import type { CollectionFormatData } from '../../types.gen';

@Injectable()
export class CustomClientCollectionFormatService {
    constructor(private readonly client: CustomClientClient) {
    }
    public async collectionFormat(options: CollectionFormatData): Promise<AxiosResponse<unknown>> {
        return await this.client.get(options.url, {
            ...options
        });
    }
}