packages:
  - docs
  - examples/**/*
  - packages/**/*

onlyBuiltDependencies:
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
  - unrs-resolver

patchedDependencies:
  vitepress: patches/vitepress.patch
