packages:
  - dev/**
  - examples/**/*
  - packages/**/*
  - web
  - '!examples/*/.output'
engineStrict: true
saveExact: true
packageConfigs:
  '@example/openapi-ts-nuxt':
    engineStrict: true
    saveExact: true
