packages:
  - docs
  - examples/**/*
  - packages/**/*

catalogs:
  dev:
    '@angular-devkit/build-angular': 19.2.18
    '@angular/animations': 19.2.15
    '@angular/cli': 19.2.18
    '@angular/common': 19.2.15
    '@angular/compiler': 19.2.15
    '@angular/compiler-cli': 19.2.15
    '@angular/core': 19.2.15
    '@angular/forms': 19.2.15
    '@angular/platform-browser': 19.2.15
    '@angular/platform-browser-dynamic': 19.2.15
    '@angular/router': 19.2.15
    '@arethetypeswrong/cli': 0.18.2
    '@changesets/cli': 2.29.7
    '@changesets/get-github-info': 0.6.0
    '@changesets/parse': 0.4.1
    '@changesets/types': 6.1.0
    '@eslint/js': 9.32.0
    '@nuxt/module-builder': 0.8.4
    '@nuxt/schema': 3.16.2
    '@nuxt/test-utils': 3.17.2
    '@pinia/colada': 0.17.6
    '@tanstack/angular-query-experimental': 5.73.3
    '@tanstack/react-query': 5.73.3
    '@tanstack/solid-query': 5.73.3
    '@tanstack/svelte-query': 5.73.3
    '@tanstack/vue-query': 5.73.3
    '@types/bun': 1.3.0
    '@types/cross-spawn': 6.0.6
    '@types/node': 22.10.5
    '@types/semver': 7.7.1
    '@typescript-eslint/eslint-plugin': 8.29.1
    '@vitest/coverage-v8': 3.1.1
    'ajv': 8.17.1
    'arktype': 2.1.23
    'axios': 1.8.2
    'cross-spawn': 7.0.6
    'dotenv': 17.2.3
    'eslint-config-prettier': 9.1.2
    'eslint-plugin-simple-import-sort': 12.1.1
    'eslint-plugin-sort-destructure-keys': 2.0.0
    'eslint-plugin-sort-keys-fix': 1.1.2
    'eslint-plugin-typescript-sort-keys': 3.3.0
    'eslint-plugin-vue': 9.32.0
    'eslint': 9.17.0
    'fastify': 5.2.0
    'glob': 11.0.3
    'globals': 16.4.0
    'husky': 9.1.7
    'lint-staged': 16.2.5
    'node-fetch': 3.3.2
    'nuxt': 3.14.1592
    'ofetch': 1.4.1
    'prettier': 3.4.2
    'rollup-plugin-dts': 6.1.1
    'rollup': 4.31.0
    'rxjs': 7.8.1
    'sharp': 0.33.5
    'ts-node': 10.9.2
    'tsdown': 0.15.8
    'tslib': 2.8.1
    'turbo': 2.5.8
    'typescript-eslint': 8.29.1
    'typescript': 5.9.3
    'valibot': 1.1.0
    'vite': 7.1.2
    'vitepress-plugin-llms': 1.7.3
    'vitepress': 2.0.0-alpha.12
    'vitest': 3.2.4
    'vue': 3.5.13
    'yaml': 2.8.0
    'zod': 4.1.12
    'zone.js': 0.15.1
  docs:
    '@stackblitz/sdk': 1.11.0
    'vue3-select-component': 0.11.8
  nuxt:
    '@nuxt/kit': 3.15.4
    'defu': 6.1.4
    'mlly': 1.8.0
    'nuxt': '>=3.0.0'
    'vue': '>=3.5.13'
  peer:
    'typescript': '>=5.5.3'
  prod:
    '@hey-api/json-schema-ref-parser': 1.2.1
    'ansi-colors': 4.1.3
    'c12': 3.3.1
    'color-support': 1.1.3
    'commander': 14.0.1
    'handlebars': 4.7.8
    'open': 10.2.0
    'semver': 7.7.2
  zod3:
    'zod': '^3.25.0'

patchedDependencies:
  vitepress: patches/vitepress.patch
