// This file is auto-generated by @hey-api/openapi-ts

import { useQuery, type UseQueryOptions, useMutation, type UseMutationOptions } from '@pinia/colada';
import { toRef } from 'vue';
import type { ExportData, PatchApiVbyApiVersionNoTagData, ImportResponse, ImportData, FooWowData, GetApiVbyApiVersionSimpleOperationResponse, GetApiVbyApiVersionSimpleOperationError, GetApiVbyApiVersionSimpleOperationData } from '../../types.gen';
import { client } from '@pinia/colada/client';

export const useExportQuery = async (params: {}, options?: UseQueryOptions<unknown, unknown, ExportData>) => {
    const query = useQuery({
        query: client({
            method: 'get',
            url: '/api/v{api-version}/no+tag'
        }),
        key: [
            'default',
            'export'
        ],
        ...options
    });
    return {
        ...query
    };
};

export const usePatchApiVbyApiVersionNoTagQuery = async (params: {}, options?: UseQueryOptions<unknown, unknown, PatchApiVbyApiVersionNoTagData>) => {
    const query = useQuery({
        query: client({
            method: 'patch',
            url: '/api/v{api-version}/no+tag'
        }),
        key: [
            'default',
            'patchApiVbyApiVersionNoTag'
        ],
        ...options
    });
    return {
        ...query
    };
};

export const useImportMutation = async (params: {}, options?: UseMutationOptions<ImportResponse, ImportData, unknown>) => {
    const bodyRef = toRef(params?.body);
    const mutation = useMutation({
        mutation: client({
            method: 'post',
            url: '/api/v{api-version}/no+tag',
            bodyRef
        }),
        key: [
            'default',
            'import',
            bodyRef
        ],
        ...options
    });
    return {
        ...mutation,
        body: bodyRef
    };
};

export const useFooWowQuery = async (params: {}, options?: UseQueryOptions<unknown, unknown, FooWowData>) => {
    const query = useQuery({
        query: client({
            method: 'put',
            url: '/api/v{api-version}/no+tag'
        }),
        key: [
            'default',
            'fooWow'
        ],
        ...options
    });
    return {
        ...query
    };
};

export const useGetApiVbyApiVersionSimpleOperationQuery = async (params: {}, options?: UseQueryOptions<GetApiVbyApiVersionSimpleOperationResponse, GetApiVbyApiVersionSimpleOperationError, GetApiVbyApiVersionSimpleOperationData>) => {
    const pathRef = toRef(params?.path);
    const query = useQuery({
        query: client({
            method: 'get',
            url: '/api/v{api-version}/simple:operation',
            pathRef
        }),
        key: [
            'default',
            'getApiVbyApiVersionSimpleOperation',
            pathRef
        ],
        ...options
    });
    return {
        ...query,
        path: pathRef
    };
};