swagger: '2.0'
info:
  title: OpenAPI 2.0 security api key example
  version: '1'
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
      security:
        - foo: []
securityDefinitions:
  foo:
    in: query
    name: foo
    type: apiKey
