swagger: 2.0
info:
  title: OpenAPI 2.0 servers host example
  version: 1
host: foo.com
paths:
  /foo:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
