openapi: 3.1.0
info:
  title: discriminator allOf member example
  version: 0.0.0
paths:
  /notification:
    get:
      operationId: getNotification
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotificationDeleteContent'
components:
  schemas:
    UserNotificationDeleteContent:
      oneOf:
        - $ref: '#/components/schemas/UserNotificationDeleteContentRunning'
        - $ref: '#/components/schemas/UserNotificationDeleteContentSuccess'
        - $ref: '#/components/schemas/UserNotificationDeleteContentError'
      discriminator:
        propertyName: status
        mapping:
          running: '#/components/schemas/UserNotificationDeleteContentRunning'
          success: '#/components/schemas/UserNotificationDeleteContentSuccess'
          error: '#/components/schemas/UserNotificationDeleteContentError'
    UserNotificationDeleteContentBase:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    UserNotificationDeleteContentError:
      allOf:
        - $ref: '#/components/schemas/UserNotificationDeleteContentBase'
        - type: object
          required:
            - finishedAt
            - error
          properties:
            finishedAt:
              type: string
              format: date-time
            error:
              type: string
    UserNotificationDeleteContentRunning:
      allOf:
        - $ref: '#/components/schemas/UserNotificationDeleteContentBase'
        - type: object
          required:
            - startedAt
          properties:
            startedAt:
              type: string
              format: date-time
    UserNotificationDeleteContentSuccess:
      allOf:
        - $ref: '#/components/schemas/UserNotificationDeleteContentBase'
        - type: object
          required:
            - finishedAt
          properties:
            finishedAt:
              type: string
              format: date-time
