openapi: 3.1.1
info:
  title: OpenAPI 3.1.1 parameter content example
  version: '1'
paths:
  /foo:
    get:
      parameters:
        - name: foo
          in: query
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string
                  bar:
                    type: boolean
      responses:
        default:
          description: OK
    post:
      parameters:
        - name: foo
          in: query
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string
      responses:
        default:
          description: OK
