openapi: 3.1.1
info:
  title: OpenAPI 3.1.1 security api key example
  version: '1'
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
      security:
        - foo: []
  /bar:
    get:
      responses:
        '200':
          description: OK
      security:
        - bar: []
        - MutualTLS: []
components:
  securitySchemes:
    foo:
      in: query
      name: foo
      type: apiKey
    bar:
      in: cookie
      name: bar
      type: apiKey
    MutualTLS:
      type: mutualTLS
