openapi: 3.0.1
info:
  title: foo
  description: foo
  version: '1'
components:
  schemas:
    Foo:
      type: object
      properties:
        foo:
          type: array
          items:
            type: object
            properties:
              baz:
                type: string
        bar:
          type: array
          items:
            type: object
            properties:
              baz:
                type: string
    Bar:
      type: object
      properties:
        foo:
          type: array
          items:
            $ref: '#/components/schemas/Foo/properties/foo/items'
        bar:
          type: array
          items:
            $ref: '#/components/schemas/Foo/properties/bar/items'
