openapi: '3.0.3'
info:
  title: Test components/headers
  version: 0.0.1
paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
components:
  headers:
    X-Rate-Limit:
      description: The number of allowed requests in the current period
      schema:
        type: integer
  schemas:
    Foo:
      type: object
      properties:
        rateLimit:
          $ref: '#/components/headers/X-Rate-Limit'
