openapi: 3.0.1
info:
  title: Deep Path Ref Test
  description: Test case for deep path references in #/paths/...
  version: '1'
paths:
  /users:
    get:
      operationId: getUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /posts:
    get:
      operationId: getPosts
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    # Deep path reference to /users response schema item
                    $ref: '#/paths/~1users/get/responses/200/content/application~1json/schema/items'
                  title:
                    type: string
