openapi: 3.0.3
info:
  title: Schema Name Collision Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user1:
                    $ref: '#/components/schemas/User_v1_User'
                  user2:
                    $ref: '#/components/schemas/User'
                  user3:
                    $ref: '#/components/schemas/User_v2_User'
components:
  schemas:
    User_v1_User:
      type: object
      properties:
        id:
          type: string
        version:
          type: string
          enum: ['v1']
    User:
      type: object
      properties:
        name:
          type: string
    User_v2_User:
      type: object
      properties:
        email:
          type: string
        version:
          type: string
          enum: ['v2']
