// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { getAlbums, getFoo, getProducts, type Options, postFoo } from '../sdk.gen';
import type { GetAlbumsData, GetAlbumsResponse, GetFooData, GetFooResponse, GetProductsData, GetProductsResponse, PostFooData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        _infinite?: boolean;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const getFooQueryKey = (options: Options<GetFooData>) => createQueryKey('getFoo', options);

export const getFooQuery = defineQueryOptions<Options<GetFooData>, GetFooResponse, Error>((options: Options<GetFooData>) => ({
    key: getFooQueryKey(options),
    query: async (context) => {
        const { data } = await getFoo({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const postFooMutation = (options?: Partial<Options<PostFooData>>): UseMutationOptions<unknown, Options<PostFooData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await postFoo({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getAlbumsQueryKey = (options?: Options<GetAlbumsData>) => createQueryKey('getAlbums', options);

export const getAlbumsQuery = defineQueryOptions<Options<GetAlbumsData>, GetAlbumsResponse, Error>((options?: Options<GetAlbumsData>) => ({
    key: getAlbumsQueryKey(options),
    query: async (context) => {
        const { data } = await getAlbums({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getProductsQueryKey = (options?: Options<GetProductsData>) => createQueryKey('getProducts', options);

export const getProductsQuery = defineQueryOptions<Options<GetProductsData>, GetProductsResponse, Error>((options?: Options<GetProductsData>) => ({
    key: getProductsQueryKey(options),
    query: async (context) => {
        const { data } = await getProducts({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
