/* eslint-disable @typescript-eslint/no-unused-vars, arrow-body-style */
// @ts-ignore
import path from 'node:path';

// @ts-ignore
import { customClientPlugin } from '@hey-api/custom-client/plugin';
import {
  // @ts-ignore
  defineConfig,
  // @ts-ignore
  OperationPath,
  // @ts-ignore
  OperationStrategy,
  // @ts-ignore
  // reserved,
  // @ts-ignore
  utils,
} from '@hey-api/openapi-python';

// @ts-ignore
import { myClientPlugin } from '../packages/openapi-ts-tests/main/test/custom/client/plugin';
// @ts-ignore
import { getSpecsPath } from '../packages/openapi-ts-tests/utils';

// reserved.runtime.set((list) => [...list, 'Agent']);
// reserved.type.set((list) => [...list, 'Agent']);

// @ts-ignore
export default defineConfig(() => {
  // ...
  return [
    {
      input: [
        {
          // fetch: {
          //   headers: {
          //     'x-foo': 'bar',
          //   },
          // },
          // path: {
          //   components: {},
          //   info: {
          //     version: '1.0.0',
          //   },
          //   openapi: '3.1.0',
          //   paths: {},
          // },
          path: path.resolve(
            getSpecsPath(),
            // '2.0.x',
            // '3.0.x',
            '3.1.x',
            // 'circular.yaml',
            // 'dutchie.json',
            // 'enum-names-values.yaml',
            // 'full.yaml',
            // 'integer-formats.yaml',
            // 'invalid',
            // 'object-property-names.yaml',
            // 'openai.yaml',
            // 'opencode.yaml',
            // 'pagination-ref.yaml',
            // 'schema-const.yaml',
            // 'sdk-instance.yaml',
            // 'sdk-method-class-conflict.yaml',
            // 'sdk-nested-classes.yaml',
            // 'sdk-nested-conflict.yaml',
            'security-api-key.yaml',
            // 'string-with-format.yaml',
            // 'transformers.json',
            // 'transformers-recursive.json',
            // 'type-format.yaml',
            // 'validators.yaml',
            // 'validators-circular-ref.json',
            // 'validators-circular-ref-2.yaml',
            // 'zoom-video-sdk.json',
          ),
          // path: 'https://get.heyapi.dev/hey-api/backend?branch=main&version=1.0.0',
          // path: 'http://localhost:4000/',
          // path: 'http://localhost:8000/openapi.json',
          // path: 'https://mongodb-mms-prod-build-server.s3.amazonaws.com/openapi/2caffd88277a4e27c95dcefc7e3b6a63a3b03297-v2-2023-11-15.json',
          // path: 'https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml',
          // watch: {
          //   enabled: true,
          //   interval: 500,
          //   timeout: 30_000,
          // },
        },
        // path.resolve(getSpecsPath(), '3.1.x', 'full.yaml'),
        // {
        //   branch: 'main',
        //   organization: 'hey-api',
        //   path: 'hey-api/backend',
        //   project: 'backend',
        //   project: 'upload-openapi-spec',
        //   version: '1.0.0',
        // },
        // 'hey-api/backend?branch=main&version=1.0.0',
        // 'scalar:@scalar/access-service',
        // 'readme:@developers/v2.0#nysezql0wwo236',
        // 'readme:nysezql0wwo236',
        // 'https://dash.readme.com/api/v1/api-registry/nysezql0wwo236',
        // 'https://somefakedomain.com/openapi.yaml',
      ],
      logs: {
        // level: 'debug',
        path: './logs',
      },
      output: [
        {
          // case: 'snake_case',
          // clean: true,
          // fileName: {
          //   // case: 'snake_case',
          //   // name: '{{name}}.renamed',
          //   suffix: '.meh',
          // },
          // header: null,
          header: [
            '/* eslint-disable */',
            '// This file is auto-generated by @hey-api/openapi-python',
          ],
          // importFileExtension: '.js',
          // indexFile: false,
          // nameConflictResolver({ attempt, baseName }) {
          //   // console.log('resolving conflict for:', { attempt, baseName });
          //   return attempt === 0 ? baseName : `${baseName}_N${attempt + 1}`;
          // },
          path: path.resolve(__dirname, '.gen'),
          postProcess: ['eslint'],
          // preferExportAll: true,
          resolveModuleName: (moduleName) => {
            if (moduleName === 'valibot') {
              return 'valibot';
            }
            return;
          },
          source: {
            // callback(source) {
            //   console.log('Source generated, length:', source.length);
            // },
            enabled: false,
            // extension: 'yaml',
            // fileName: 'spec',
            // path: null,
            // serialize(input) {
            //   return JSON.stringify(input, null, 0);
            // },
          },
          // tsConfigPath: path.resolve(
          //   __dirname,
          //   'tsconfig',
          //   'tsconfig.nodenext.json',
          // ),
        },
        // '.gen',
      ],
      parser: {
        filters: {
          // deprecated: false,
          operations: {
            include: [
              // 'GET /event',
              // '/^[A-Z]+ /v1//',
            ],
          },
          // orphans: true,
          // preserveOrder: true,
          // schemas: {
          //   include: ['Foo'],
          // },
          // tags: {
          //   exclude: ['bar'],
          // },
        },
        hooks: {
          events: {
            // 'node:set:after': ({ node, plugin }) => {
            //   if (node) {
            //     console.log(`(${plugin.name}) set node:`, node.symbol);
            //   }
            // },
            // 'node:set:before': ({ node, plugin }) => {
            //   console.log(`(${plugin.name}) setting node:`, node?.symbol?.id);
            // },
            // 'plugin:handler:after': ({ plugin }) => {
            //   console.log(`(${plugin.name}): handler finished`);
            // },
            // 'plugin:handler:before': ({ plugin }) => {
            //   console.log(`(${plugin.name}): handler starting`);
            // },
            // 'symbol:register:after': ({ plugin, symbol }) => {
            //   console.log(`(global, ${plugin.name}) registered:`, symbol.id);
            // },
            'symbol:register:before': ({ plugin, symbol }) => {
              // if (!symbol.external && !symbol.meta?.resourceType) {
              //   console.log(`[${plugin.name}]:`, symbol.name);
              // }
              if (plugin && !symbol.external && !symbol.meta?.path) {
                // console.log(`[${plugin.name}]:`, symbol.name, symbol.meta);
              }
              // if (symbol.meta?.tags && symbol.meta?.tags.size > 0) {
              //   console.log(
              //     `[${plugin.name}]:`,
              //     symbol.name,
              //     symbol.meta.path,
              //     symbol.meta.tags,
              //   );
              // }
            },
          },
          operations: {
            getKind() {
              // noop
            },
            isMutation() {
              // noop
            },
            isQuery: (op) => {
              if (op.method === 'post' && op.path === '/search') {
                return true;
              }
              return;
            },
          },
          symbols: {
            // getFilePath: (symbol) => {
            //   if (symbol.name) {
            //     return symbol.name[0]?.toLowerCase();
            //   }
            //   return;
            // },
          },
        },
        pagination: {
          // keywords: ['aa'],
        },
        patch: {
          // operations: {
          //   'GET /foo': (operation: any) => {
          //     operation.responses['200'].description = 'foo';
          //   },
          // },
          // version: () => '3.1.1',
        },
        transforms: {
          // enums: {
          //   enabled: false,
          //   mode: 'root',
          //   // name: '{{name}}',
          // },
          // propertiesRequiredByDefault: true,
          // readWrite: {
          //   // enabled: false,
          //   requests: '{{name}}Writable',
          //   responses: '{{name}}',
          // },
        },
        // validate_EXPERIMENTAL: true,
      },
      plugins: [
        // customClientPlugin({
        //   baseUrl: false,
        // }),
        // myClientPlugin(),
        {
          // baseUrl: false,
          // exportFromIndex: true,
          // name: '@hey-api/client-angular',
          // runtimeConfigPath: path.resolve(__dirname, 'hey-api.ts'),
          // runtimeConfigPath: './src/hey-api.ts',
          // strictBaseUrl: true,
          throwOnError: true,
        },
        {
          // case: 'snake_case',
          // definitions: '你_snake_{{name}}',
          enums: {
            // case: 'PascalCase',
            // constantsIgnoreNull: true,
            // enabled: false,
            // mode: 'typescript',
          },
          // errors: {
          //   error: '他們_error_{{name}}',
          //   name: '你們_errors_{{name}}',
          // },
          // exportFromIndex: false,
          // name: '@hey-api/typescript',
          // requests: '我們_data_{{name}}',
          // responses: {
          //   name: '我_responses_{{name}}',
          //   response: '他_response_{{name}}',
          // },
          // topType: 'any',
          // tree: true,
          // webhooks: {
          //   name: 'Webby{{name}}Hook',
          //   payload: '{{name}}WebhookEvent',
          // },
        },
        {
          // auth: false,
          // client: false,
          examples: {
            // enabled: false,
            importKind: 'default',
            importName: 'CatStore',
            importSetup: ({ $, node }) =>
              $.new(
                node.name,
                $.object().pretty().prop('apiKey', $.literal('YOUR_API_KEY')),
              ),
            // language: 'TypeScript',
            moduleName: '@petstore/client',
            payload(operation, ctx) {
              const { $ } = ctx;
              if (
                operation.path === '/pet/{petId}' ||
                operation.path === '/pet'
              ) {
                return $.object().pretty().prop('petId', $.literal(1234));
              }
              return;
            },
            setupName: 'client',
            // transform: (example) => example.replace(/\({}\)/, '({\n  ...\n})'),
          },
          // getSignature: ({ fields, signature, operation }) => {
          //   // ...
          //   fields.unwrap('path')
          // },
          // include...
          name: '@hey-api/sdk',
          operations: {
            // container: 'object',
            // containerName: {
            //   // casing: 'snake_case',
            //   name: 'OpencodeClient',
            // },
            containerName: 'PetStore',
            // nesting(operation) {
            //   if (operation.path === '/pet/{petId}' || operation.path === '/pet') {
            //     return ['pet', operation.operationId?.replace(/Pet/, '') || operation.method.toLocaleLowerCase()];
            //   }
            //   return OperationPath.fromOperationId()(operation);
            // },
            // methodName: {
            //   // casing: 'SCREAMING_SNAKE_CASE',
            //   name: '{{name}}Yummy',
            // },
            // methods: 'static',
            // nesting: 'id',
            // segmentName: '{{name}}Seggy',
            strategy: 'single',
            // strategy(operation) {
            //   const locations = OperationStrategy.byTags({
            //     fallback: 'default',
            //     path: OperationPath.fromOperationId({
            //       delimiters: /[./]/,
            //     }),
            //   })(operation)
            //   return locations.map((loc) => {
            //     if (loc[0] && loc[1] && loc[0] === loc[1]) {
            //       return loc.slice(1);
            //     }
            //     return loc;
            //   });
            // },
            // strategyDefaultTag: 'DaxLikedThis',
          },
          paramsStructure: 'flat',
          // responseStyle: 'data',
          // signature: 'auto',
          // signature: 'client',
          // signature: 'object',
          // transformer: '@hey-api/transformers',
          // transformer: true,
          // validator: 'valibot',
          // validator: {
          //   request: 'zod',
          //   response: 'zod',
          // },
          '~hooks': {
            symbols: {
              // getFilePath: (symbol) => {
              //   if (symbol.name) {
              //     return utils.toCase(symbol.name, 'camelCase');
              //   }
              //   return;
              // },
            },
          },
        },
      ],
      // watch: 3_000,
    },
    // {
    //   input: 'scalar:@scalar/access-service',
    //   logs: {
    //     // level: 'debug',
    //     path: './logs',
    //   },
    //   output: '.gen',
    // },
  ];
});
