// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zBaz = z._default(z.readonly(z.string().check(z.regex(/foo\nbar/))), 'baz');

export const zFoo = z._default(z.union([
    z.object({
        foo: z.optional(z.string().check(z.regex(/^\d{3}-\d{2}-\d{4}$/))),
        get bar() {
            return z.optional(z.lazy((): any => zBar2));
        },
        get baz() {
            return z.optional(z.array(z.lazy((): any => zFoo2)));
        },
        qux: z._default(z.optional(z.int().check(z.gt(0))), 0)
    }),
    z.null()
]), null);

export const zBar = z.object({
    foo: z.optional(zFoo)
});
