// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod/v4';

export const zBar = z.string();

export const zFoo = z.object({
    foo: z.optional(z.array(zBar).min(1).max(2147483647))
});