import { compiler } from '../../compiler';

export const identifiers = {
  and: compiler.identifier({ text: 'and' }),
  array: compiler.identifier({ text: 'array' }),
  bigint: compiler.identifier({ text: 'bigint' }),
  boolean: compiler.identifier({ text: 'boolean' }),
  coerce: compiler.identifier({ text: 'coerce' }),
  datetime: compiler.identifier({ text: 'datetime' }),
  default: compiler.identifier({ text: 'default' }),
  describe: compiler.identifier({ text: 'describe' }),
  enum: compiler.identifier({ text: 'enum' }),
  gt: compiler.identifier({ text: 'gt' }),
  gte: compiler.identifier({ text: 'gte' }),
  infer: compiler.identifier({ text: 'infer' }),
  int: compiler.identifier({ text: 'int' }),
  intersection: compiler.identifier({ text: 'intersection' }),
  ip: compiler.identifier({ text: 'ip' }),
  lazy: compiler.identifier({ text: 'lazy' }),
  length: compiler.identifier({ text: 'length' }),
  literal: compiler.identifier({ text: 'literal' }),
  lt: compiler.identifier({ text: 'lt' }),
  lte: compiler.identifier({ text: 'lte' }),
  max: compiler.identifier({ text: 'max' }),
  min: compiler.identifier({ text: 'min' }),
  never: compiler.identifier({ text: 'never' }),
  null: compiler.identifier({ text: 'null' }),
  nullable: compiler.identifier({ text: 'nullable' }),
  number: compiler.identifier({ text: 'number' }),
  object: compiler.identifier({ text: 'object' }),
  optional: compiler.identifier({ text: 'optional' }),
  parseAsync: compiler.identifier({ text: 'parseAsync' }),
  readonly: compiler.identifier({ text: 'readonly' }),
  record: compiler.identifier({ text: 'record' }),
  regex: compiler.identifier({ text: 'regex' }),
  string: compiler.identifier({ text: 'string' }),
  tuple: compiler.identifier({ text: 'tuple' }),
  undefined: compiler.identifier({ text: 'undefined' }),
  union: compiler.identifier({ text: 'union' }),
  unknown: compiler.identifier({ text: 'unknown' }),
  url: compiler.identifier({ text: 'url' }),
  void: compiler.identifier({ text: 'void' }),
  z: compiler.identifier({ text: 'z' }),
};

export const zodId = 'zod';
