// This file is auto-generated by @hey-api/openapi-ts

export type PostTestData = {
    /**
     * should not produce duplicate null
     */
    body?: {
        weirdEnum?: ('' | (string) | null);
    };
};

export type $OpenApiTs = {
    '/test': {
        post: {
            req: PostTestData;
        };
    };
};