// This file is auto-generated by @hey-api/openapi-ts

export type { ClientOptions, ModelMapWithDeclaredData, ModelMapWithDeclaredResponse, ModelMapWithDeclaredResponse2, ModelMapWithDeclaredResponses } from './types.gen';
