// This file is auto-generated by @hey-api/openapi-ts

const quxSchemaResponseTransformer = (data: any) => {
    if (data.baz) {
        data.baz = new Date(data.baz);
    }
    return data;
};

const bazSchemaResponseTransformer = (data: any) => {
    data.bar = new Date(data.bar);
    return data;
};
