// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/v4-mini';

export const zArrayWithAllOfObjects = z.array(z.intersection(z.object({
    id: z.optional(z.int())
}), z.object({
    name: z.optional(z.string())
})));

export const zArrayWithAllOfPrimitives = z.array(z.intersection(z.number(), z.string()));

export const zBaseModel = z.object({
    id: z.optional(z.int()),
    createdAt: z.optional(z.iso.datetime())
});

export const zArrayWithAllOfRefs = z.array(z.intersection(zBaseModel, z.object({
    extra: z.optional(z.string())
})));
