swagger: 2.0
info:
  title: OpenAPI 2.0 security oauth2 example
  version: 1
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
      security:
        - foo: []
securityDefinitions:
  foo:
    flow: 'password'
    scopes: {}
    tokenUrl: '/'
    type: 'oauth2'
