swagger: 2.0
info:
  title: OpenAPI 2.0 servers base path example
  version: 1
basePath: /v1
paths:
  /foo:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
