// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.example.com' | (string & {});
};

export type NodeTemplate<nodeType> = {
    id: string;
    child?: nodeType;
};

export interface Branch extends NodeTemplate<Branch> {
    name: string;
    level?: number;
}

export type Leaf = {
    id: string;
    value?: string;
};

export type GetBranchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/branches';
};

export type GetBranchesResponses = {
    /**
     * Branch list
     */
    200: Array<Branch>;
};

export type GetBranchesResponse = GetBranchesResponses[keyof GetBranchesResponses];
