// This file is auto-generated by @hey-api/openapi-ts

export type Foo = {
    type?: TypeEnum;
};

export type TypeEnum = 'foo' | 'bar';

export const TypeEnum = {
    FOO: 'foo',
    BAR: 'bar'
} as const;

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};