// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * This is Bar schema.
 */
export const zBar: z.AnyZodObject = z.object({
    foo: z.lazy(() => {
        return zFoo;
    }).optional()
});

/**
 * This is Foo schema.
 */
export const zFoo: z.ZodTypeAny = z.union([
    z.object({
        foo: z.string().regex(/^\d{3}-\d{2}-\d{4}$/).optional(),
        bar: zBar.optional(),
        baz: z.array(z.lazy(() => {
            return zFoo;
        })).optional(),
        qux: z.number().int().gt(0).optional().default(0)
    }),
    z.null()
]).default(null);

export const zBaz = z.string().regex(/foo\nbar/).readonly().default('baz');

/**
 * This is Foo parameter.
 */
export const zFoo2 = z.string();

export const zFoo3 = z.object({
    foo: zBar.optional()
});

export const zPatchFooData = z.object({
    foo: z.string().optional()
});

/**
 * This is Foo parameter.
 */
export const zPatchFooParameterFooData = z.string();

export const zPatchFooParameterBarData = zBar;

export const zPatchFooParameterBazData = z.object({
    baz: z.string().optional()
});

export const zPatchFooParameterQuxData = z.string().date();

export const zPatchFooParameterQuuxData = z.string().datetime();

export const zFooData = z.unknown();

export const zPostFooData = zFooData;