// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type FooRead = BarRead & {
    readonly foo?: string;
};

export type BarRead = Baz & {
    readonly bar?: string;
};

export type Baz = {
    baz?: string;
};

export type QuxAllRead = {
    readonly baz?: string;
};

export type Quux = {
    baz?: Array<Baz>;
    qux?: QuxAllRead;
};

export type Corge = {
    foo?: string;
    bar?: {
        readonly baz?: boolean;
    };
};

export type PostFooReadData = {
    body: FooRead;
    path?: never;
    query?: never;
    url: '/foo-read';
};

export type PostFooReadResponses = {
    /**
     * OK
     */
    200: FooRead;
};

export type PostFooReadResponse = PostFooReadResponses[keyof PostFooReadResponses];
