openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: A test API for testing spec comparison
servers:
  - url: https://api.example.com/v1
    description: Production server
security:
  - apiKey: []
paths:
  /users:
    get:
      summary: Get all users
      parameters:
        - name: limit
          in: query
          description: Number of users to return
          required: true
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Number of users to skip
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  name: John Doe
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header
