// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { ServiceWithEmptyTagData, DeleteCallWithoutParametersAndResponseData, GetCallWithoutParametersAndResponseData, HeadCallWithoutParametersAndResponseData, OptionsCallWithoutParametersAndResponseData, PatchCallWithoutParametersAndResponseData, PostCallWithoutParametersAndResponseData, PutCallWithoutParametersAndResponseData, CallWithDescriptionsData, CallWithParametersData, CallWithWeirdParameterNamesData, CallWithDefaultParametersData, CallWithDefaultOptionalParametersData, CallToTestOrderOfParamsData, DuplicateNameData, DuplicateName2Data, DuplicateName3Data, DuplicateName4Data, CallWithNoContentResponseData, CallWithResponseAndNoContentResponseData, CallWithResponseAndNoContentResponseResponse, DummyAData, DummyBData, CallWithResponseData, CallWithResponseResponse, CallWithDuplicateResponsesData, CallWithDuplicateResponsesError, CallWithDuplicateResponsesResponse, CallWithResponsesData, CallWithResponsesError, CallWithResponsesResponse, CollectionFormatData, TypesData, TypesResponse, ComplexTypesData, ComplexTypesResponse, CallWithResultFromHeaderData, TestErrorCodeData, NonAsciiæøåÆøÅöôêÊ字符串Data, NonAsciiæøåÆøÅöôêÊ字符串Response, PostApiVbyApiVersionBodyData, PostApiVbyApiVersionBodyError, PostApiVbyApiVersionBodyResponse } from './types.gen';

export const client = createClient(createConfig());

export class DefaultService {
    public static serviceWithEmptyTag<ThrowOnError extends boolean = false>(options?: Options<ServiceWithEmptyTagData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/no-tag'
        });
    }
    
    /**
     * Body should not be unknown
     * Body should not be unknown
     */
    public static postApiVbyApiVersionBody<ThrowOnError extends boolean = false>(options: Options<PostApiVbyApiVersionBodyData, ThrowOnError>) {
        return (options?.client ?? client).post<PostApiVbyApiVersionBodyResponse, PostApiVbyApiVersionBodyError, ThrowOnError>({
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            },
            url: '/api/v{api-version}/body'
        });
    }
    
}

export class SimpleService {
    public static deleteCallWithoutParametersAndResponse<ThrowOnError extends boolean = false>(options?: Options<DeleteCallWithoutParametersAndResponseData, ThrowOnError>) {
        return (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/simple'
        });
    }
    
    public static getCallWithoutParametersAndResponse<ThrowOnError extends boolean = false>(options?: Options<GetCallWithoutParametersAndResponseData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/simple'
        });
    }
    
    public static headCallWithoutParametersAndResponse<ThrowOnError extends boolean = false>(options?: Options<HeadCallWithoutParametersAndResponseData, ThrowOnError>) {
        return (options?.client ?? client).head<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/simple'
        });
    }
    
    public static optionsCallWithoutParametersAndResponse<ThrowOnError extends boolean = false>(options?: Options<OptionsCallWithoutParametersAndResponseData, ThrowOnError>) {
        return (options?.client ?? client).options<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/simple'
        });
    }
    
    public static patchCallWithoutParametersAndResponse<ThrowOnError extends boolean = false>(options?: Options<PatchCallWithoutParametersAndResponseData, ThrowOnError>) {
        return (options?.client ?? client).patch<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/simple'
        });
    }
    
    public static postCallWithoutParametersAndResponse<ThrowOnError extends boolean = false>(options?: Options<PostCallWithoutParametersAndResponseData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/simple'
        });
    }
    
    public static putCallWithoutParametersAndResponse<ThrowOnError extends boolean = false>(options?: Options<PutCallWithoutParametersAndResponseData, ThrowOnError>) {
        return (options?.client ?? client).put<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/simple'
        });
    }
    
}

export class DescriptionsService {
    public static callWithDescriptions<ThrowOnError extends boolean = false>(options?: Options<CallWithDescriptionsData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/descriptions/'
        });
    }
    
}

export class ParametersService {
    public static callWithParameters<ThrowOnError extends boolean = false>(options: Options<CallWithParametersData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/parameters/{parameterPath}'
        });
    }
    
    public static callWithWeirdParameterNames<ThrowOnError extends boolean = false>(options: Options<CallWithWeirdParameterNamesData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}'
        });
    }
    
}

export class DefaultsService {
    public static callWithDefaultParameters<ThrowOnError extends boolean = false>(options: Options<CallWithDefaultParametersData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/defaults'
        });
    }
    
    public static callWithDefaultOptionalParameters<ThrowOnError extends boolean = false>(options?: Options<CallWithDefaultOptionalParametersData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/defaults'
        });
    }
    
    public static callToTestOrderOfParams<ThrowOnError extends boolean = false>(options: Options<CallToTestOrderOfParamsData, ThrowOnError>) {
        return (options?.client ?? client).put<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/defaults'
        });
    }
    
}

export class DuplicateService {
    public static duplicateName<ThrowOnError extends boolean = false>(options?: Options<DuplicateNameData, ThrowOnError>) {
        return (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/duplicate'
        });
    }
    
    public static duplicateName2<ThrowOnError extends boolean = false>(options?: Options<DuplicateName2Data, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/duplicate'
        });
    }
    
    public static duplicateName3<ThrowOnError extends boolean = false>(options?: Options<DuplicateName3Data, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/duplicate'
        });
    }
    
    public static duplicateName4<ThrowOnError extends boolean = false>(options?: Options<DuplicateName4Data, ThrowOnError>) {
        return (options?.client ?? client).put<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/duplicate'
        });
    }
    
}

export class NoContentService {
    public static callWithNoContentResponse<ThrowOnError extends boolean = false>(options?: Options<CallWithNoContentResponseData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/no-content'
        });
    }
    
    public static callWithResponseAndNoContentResponse<ThrowOnError extends boolean = false>(options?: Options<CallWithResponseAndNoContentResponseData, ThrowOnError>) {
        return (options?.client ?? client).get<CallWithResponseAndNoContentResponseResponse, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/multiple-tags/response-and-no-content'
        });
    }
    
}

export class ResponseService {
    public static callWithResponseAndNoContentResponse<ThrowOnError extends boolean = false>(options?: Options<CallWithResponseAndNoContentResponseData, ThrowOnError>) {
        return (options?.client ?? client).get<CallWithResponseAndNoContentResponseResponse, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/multiple-tags/response-and-no-content'
        });
    }
    
    public static callWithResponse<ThrowOnError extends boolean = false>(options?: Options<CallWithResponseData, ThrowOnError>) {
        return (options?.client ?? client).get<CallWithResponseResponse, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/response'
        });
    }
    
    public static callWithDuplicateResponses<ThrowOnError extends boolean = false>(options?: Options<CallWithDuplicateResponsesData, ThrowOnError>) {
        return (options?.client ?? client).post<CallWithDuplicateResponsesResponse, CallWithDuplicateResponsesError, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/response'
        });
    }
    
    public static callWithResponses<ThrowOnError extends boolean = false>(options?: Options<CallWithResponsesData, ThrowOnError>) {
        return (options?.client ?? client).put<CallWithResponsesResponse, CallWithResponsesError, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/response'
        });
    }
    
}

export class MultipleTags1Service {
    public static dummyA<ThrowOnError extends boolean = false>(options?: Options<DummyAData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/multiple-tags/a'
        });
    }
    
    public static dummyB<ThrowOnError extends boolean = false>(options?: Options<DummyBData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/multiple-tags/b'
        });
    }
    
}

export class MultipleTags2Service {
    public static dummyA<ThrowOnError extends boolean = false>(options?: Options<DummyAData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/multiple-tags/a'
        });
    }
    
    public static dummyB<ThrowOnError extends boolean = false>(options?: Options<DummyBData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/multiple-tags/b'
        });
    }
    
}

export class MultipleTags3Service {
    public static dummyB<ThrowOnError extends boolean = false>(options?: Options<DummyBData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/multiple-tags/b'
        });
    }
    
}

export class CollectionFormatService {
    public static collectionFormat<ThrowOnError extends boolean = false>(options: Options<CollectionFormatData, ThrowOnError>) {
        return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
            ...options,
            querySerializer: {
                array: {
                    explode: false,
                    style: 'form'
                }
            },
            url: '/api/v{api-version}/collectionFormat'
        });
    }
    
}

export class TypesService {
    public static types<ThrowOnError extends boolean = false>(options: Options<TypesData, ThrowOnError>) {
        return (options?.client ?? client).get<TypesResponse, unknown, ThrowOnError>({
            ...options,
            querySerializer: {
                array: {
                    explode: false,
                    style: 'form'
                }
            },
            url: '/api/v{api-version}/types'
        });
    }
    
}

export class ComplexService {
    public static complexTypes<ThrowOnError extends boolean = false>(options: Options<ComplexTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<ComplexTypesResponse, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/complex'
        });
    }
    
}

export class HeaderService {
    public static callWithResultFromHeader<ThrowOnError extends boolean = false>(options?: Options<CallWithResultFromHeaderData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/header'
        });
    }
    
}

export class ErrorService {
    public static testErrorCode<ThrowOnError extends boolean = false>(options: Options<TestErrorCodeData, ThrowOnError>) {
        return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/error'
        });
    }
    
}

export class NonAsciiÆøåÆøÅöôêÊService {
    public static nonAsciiæøåÆøÅöôêÊ字符串<ThrowOnError extends boolean = false>(options: Options<NonAsciiæøåÆøÅöôêÊ字符串Data, ThrowOnError>) {
        return (options?.client ?? client).post<NonAsciiæøåÆøÅöôêÊ字符串Response, unknown, ThrowOnError>({
            ...options,
            url: '/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串'
        });
    }
    
}