// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { apiVVersionODataControllerCount, callToTestOrderOfParams, callWithDefaultOptionalParameters, callWithDefaultParameters, callWithDescriptions, callWithDuplicateResponses, callWithNoContentResponse, callWithParameters, callWithResponse, callWithResponseAndNoContentResponse, callWithResponses, callWithResultFromHeader, callWithWeirdParameterNames, collectionFormat, complexParams, complexTypes, deleteCallWithoutParametersAndResponse, deleteFoo, deprecatedCall, dummyA, dummyB, duplicateName, duplicateName2, duplicateName3, duplicateName4, export_, fileResponse, fooWow, getApiVbyApiVersionSimpleOperation, getCallWithOptionalParam, getCallWithoutParametersAndResponse, import_, multipartRequest, multipartResponse, nonAsciiæøåÆøÅöôêÊ字符串, type Options, patchApiVbyApiVersionNoTag, patchCallWithoutParametersAndResponse, postApiVbyApiVersionFormData, postApiVbyApiVersionRequestBody, postCallWithOptionalParam, postCallWithoutParametersAndResponse, putCallWithoutParametersAndResponse, putWithFormUrlEncoded, testErrorCode, types, uploadFile } from '../sdk.gen';
import type { ApiVVersionODataControllerCountData, CallToTestOrderOfParamsData, CallWithDefaultOptionalParametersData, CallWithDefaultParametersData, CallWithDescriptionsData, CallWithDuplicateResponsesData, CallWithDuplicateResponsesError, CallWithDuplicateResponsesResponse, CallWithNoContentResponseData, CallWithParametersData, CallWithResponseAndNoContentResponseData, CallWithResponseData, CallWithResponsesData, CallWithResponsesError, CallWithResponsesResponse, CallWithResultFromHeaderData, CallWithWeirdParameterNamesData, CollectionFormatData, ComplexParamsData, ComplexParamsResponse, ComplexTypesData, DeleteCallWithoutParametersAndResponseData, DeleteFooData3, DeprecatedCallData, DummyAData, DummyBData, DuplicateName2Data, DuplicateName3Data, DuplicateName4Data, DuplicateNameData, ExportData, FileResponseData, FooWowData, GetApiVbyApiVersionSimpleOperationData, GetCallWithOptionalParamData, GetCallWithoutParametersAndResponseData, ImportData, ImportResponse, MultipartRequestData, MultipartResponseData, NonAsciiæøåÆøÅöôêÊ字符串Data, NonAsciiæøåÆøÅöôêÊ字符串Response, PatchApiVbyApiVersionNoTagData, PatchCallWithoutParametersAndResponseData, PostApiVbyApiVersionFormDataData, PostApiVbyApiVersionRequestBodyData, PostCallWithOptionalParamData, PostCallWithOptionalParamResponse, PostCallWithoutParametersAndResponseData, PutCallWithoutParametersAndResponseData, PutWithFormUrlEncodedData, TestErrorCodeData, TypesData, UploadFileData, UploadFileResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const exportQueryKey = (options?: Options<ExportData>) => createQueryKey('export', options);

export const exportOptions = (options?: Options<ExportData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await export_({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: exportQueryKey(options)
    });
};

export const patchApiVbyApiVersionNoTagMutation = (options?: Partial<Options<PatchApiVbyApiVersionNoTagData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<PatchApiVbyApiVersionNoTagData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await patchApiVbyApiVersionNoTag({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const importMutation = (options?: Partial<Options<ImportData>>): UseMutationOptions<{data: ImportResponse, response: Response, request: Request }, DefaultError, Options<ImportData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await import_({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const fooWowMutation = (options?: Partial<Options<FooWowData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<FooWowData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await fooWow({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const apiVVersionODataControllerCountQueryKey = (options?: Options<ApiVVersionODataControllerCountData>) => createQueryKey('apiVVersionODataControllerCount', options);

export const apiVVersionODataControllerCountOptions = (options?: Options<ApiVVersionODataControllerCountData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await apiVVersionODataControllerCount({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: apiVVersionODataControllerCountQueryKey(options)
    });
};

export const getApiVbyApiVersionSimpleOperationQueryKey = (options: Options<GetApiVbyApiVersionSimpleOperationData>) => createQueryKey('getApiVbyApiVersionSimpleOperation', options);

export const getApiVbyApiVersionSimpleOperationOptions = (options: Options<GetApiVbyApiVersionSimpleOperationData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await getApiVbyApiVersionSimpleOperation({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: getApiVbyApiVersionSimpleOperationQueryKey(options)
    });
};

export const deleteCallWithoutParametersAndResponseMutation = (options?: Partial<Options<DeleteCallWithoutParametersAndResponseData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<DeleteCallWithoutParametersAndResponseData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await deleteCallWithoutParametersAndResponse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const getCallWithoutParametersAndResponseQueryKey = (options?: Options<GetCallWithoutParametersAndResponseData>) => createQueryKey('getCallWithoutParametersAndResponse', options);

export const getCallWithoutParametersAndResponseOptions = (options?: Options<GetCallWithoutParametersAndResponseData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await getCallWithoutParametersAndResponse({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: getCallWithoutParametersAndResponseQueryKey(options)
    });
};

export const patchCallWithoutParametersAndResponseMutation = (options?: Partial<Options<PatchCallWithoutParametersAndResponseData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<PatchCallWithoutParametersAndResponseData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await patchCallWithoutParametersAndResponse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const postCallWithoutParametersAndResponseMutation = (options?: Partial<Options<PostCallWithoutParametersAndResponseData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<PostCallWithoutParametersAndResponseData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await postCallWithoutParametersAndResponse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const putCallWithoutParametersAndResponseMutation = (options?: Partial<Options<PutCallWithoutParametersAndResponseData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<PutCallWithoutParametersAndResponseData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await putCallWithoutParametersAndResponse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const deleteFooMutation = (options?: Partial<Options<DeleteFooData3>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<DeleteFooData3>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await deleteFoo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callWithDescriptionsMutation = (options?: Partial<Options<CallWithDescriptionsData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<CallWithDescriptionsData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callWithDescriptions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

/**
 * @deprecated
 */
export const deprecatedCallMutation = (options?: Partial<Options<DeprecatedCallData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<DeprecatedCallData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await deprecatedCall({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callWithParametersMutation = (options?: Partial<Options<CallWithParametersData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<CallWithParametersData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callWithParameters({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callWithWeirdParameterNamesMutation = (options?: Partial<Options<CallWithWeirdParameterNamesData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<CallWithWeirdParameterNamesData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callWithWeirdParameterNames({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const getCallWithOptionalParamQueryKey = (options: Options<GetCallWithOptionalParamData>) => createQueryKey('getCallWithOptionalParam', options);

export const getCallWithOptionalParamOptions = (options: Options<GetCallWithOptionalParamData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await getCallWithOptionalParam({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: getCallWithOptionalParamQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getCallWithOptionalParamInfiniteQueryKey = (options: Options<GetCallWithOptionalParamData>): QueryKey<Options<GetCallWithOptionalParamData>> => createQueryKey('getCallWithOptionalParam', options, true);

export const getCallWithOptionalParamInfiniteOptions = (options: Options<GetCallWithOptionalParamData>) => {
    return infiniteQueryOptions<unknown, DefaultError, InfiniteData<unknown>, QueryKey<Options<GetCallWithOptionalParamData>>, number | Pick<QueryKey<Options<GetCallWithOptionalParamData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetCallWithOptionalParamData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            return await getCallWithOptionalParam({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
        },
        queryKey: getCallWithOptionalParamInfiniteQueryKey(options)
    });
};

export const postCallWithOptionalParamMutation = (options?: Partial<Options<PostCallWithOptionalParamData>>): UseMutationOptions<{data: PostCallWithOptionalParamResponse, response: Response, request: Request }, DefaultError, Options<PostCallWithOptionalParamData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await postCallWithOptionalParam({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const postApiVbyApiVersionRequestBodyMutation = (options?: Partial<Options<PostApiVbyApiVersionRequestBodyData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<PostApiVbyApiVersionRequestBodyData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await postApiVbyApiVersionRequestBody({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const postApiVbyApiVersionFormDataMutation = (options?: Partial<Options<PostApiVbyApiVersionFormDataData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<PostApiVbyApiVersionFormDataData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await postApiVbyApiVersionFormData({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callWithDefaultParametersQueryKey = (options?: Options<CallWithDefaultParametersData>) => createQueryKey('callWithDefaultParameters', options);

export const callWithDefaultParametersOptions = (options?: Options<CallWithDefaultParametersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await callWithDefaultParameters({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: callWithDefaultParametersQueryKey(options)
    });
};

export const callWithDefaultOptionalParametersMutation = (options?: Partial<Options<CallWithDefaultOptionalParametersData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<CallWithDefaultOptionalParametersData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callWithDefaultOptionalParameters({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callToTestOrderOfParamsMutation = (options?: Partial<Options<CallToTestOrderOfParamsData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<CallToTestOrderOfParamsData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callToTestOrderOfParams({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const duplicateNameMutation = (options?: Partial<Options<DuplicateNameData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<DuplicateNameData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await duplicateName({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const duplicateName2QueryKey = (options?: Options<DuplicateName2Data>) => createQueryKey('duplicateName2', options);

export const duplicateName2Options = (options?: Options<DuplicateName2Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await duplicateName2({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: duplicateName2QueryKey(options)
    });
};

export const duplicateName3Mutation = (options?: Partial<Options<DuplicateName3Data>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<DuplicateName3Data>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await duplicateName3({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const duplicateName4Mutation = (options?: Partial<Options<DuplicateName4Data>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<DuplicateName4Data>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await duplicateName4({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callWithNoContentResponseQueryKey = (options?: Options<CallWithNoContentResponseData>) => createQueryKey('callWithNoContentResponse', options);

export const callWithNoContentResponseOptions = (options?: Options<CallWithNoContentResponseData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await callWithNoContentResponse({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: callWithNoContentResponseQueryKey(options)
    });
};

export const callWithResponseAndNoContentResponseQueryKey = (options?: Options<CallWithResponseAndNoContentResponseData>) => createQueryKey('callWithResponseAndNoContentResponse', options);

export const callWithResponseAndNoContentResponseOptions = (options?: Options<CallWithResponseAndNoContentResponseData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await callWithResponseAndNoContentResponse({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: callWithResponseAndNoContentResponseQueryKey(options)
    });
};

export const dummyAQueryKey = (options?: Options<DummyAData>) => createQueryKey('dummyA', options);

export const dummyAOptions = (options?: Options<DummyAData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await dummyA({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: dummyAQueryKey(options)
    });
};

export const dummyBQueryKey = (options?: Options<DummyBData>) => createQueryKey('dummyB', options);

export const dummyBOptions = (options?: Options<DummyBData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await dummyB({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: dummyBQueryKey(options)
    });
};

export const callWithResponseQueryKey = (options?: Options<CallWithResponseData>) => createQueryKey('callWithResponse', options);

export const callWithResponseOptions = (options?: Options<CallWithResponseData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await callWithResponse({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: callWithResponseQueryKey(options)
    });
};

export const callWithDuplicateResponsesMutation = (options?: Partial<Options<CallWithDuplicateResponsesData>>): UseMutationOptions<{data: CallWithDuplicateResponsesResponse, response: Response, request: Request }, CallWithDuplicateResponsesError, Options<CallWithDuplicateResponsesData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callWithDuplicateResponses({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callWithResponsesMutation = (options?: Partial<Options<CallWithResponsesData>>): UseMutationOptions<{data: CallWithResponsesResponse, response: Response, request: Request }, CallWithResponsesError, Options<CallWithResponsesData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callWithResponses({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const collectionFormatQueryKey = (options: Options<CollectionFormatData>) => createQueryKey('collectionFormat', options);

export const collectionFormatOptions = (options: Options<CollectionFormatData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await collectionFormat({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: collectionFormatQueryKey(options)
    });
};

export const typesQueryKey = (options: Options<TypesData>) => createQueryKey('types', options);

export const typesOptions = (options: Options<TypesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await types({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: typesQueryKey(options)
    });
};

export const uploadFileMutation = (options?: Partial<Options<UploadFileData>>): UseMutationOptions<{data: UploadFileResponse, response: Response, request: Request }, DefaultError, Options<UploadFileData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await uploadFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const fileResponseQueryKey = (options: Options<FileResponseData>) => createQueryKey('fileResponse', options);

export const fileResponseOptions = (options: Options<FileResponseData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await fileResponse({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: fileResponseQueryKey(options)
    });
};

export const complexTypesQueryKey = (options: Options<ComplexTypesData>) => createQueryKey('complexTypes', options);

export const complexTypesOptions = (options: Options<ComplexTypesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await complexTypes({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: complexTypesQueryKey(options)
    });
};

export const multipartResponseQueryKey = (options?: Options<MultipartResponseData>) => createQueryKey('multipartResponse', options);

export const multipartResponseOptions = (options?: Options<MultipartResponseData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            return await multipartResponse({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
        },
        queryKey: multipartResponseQueryKey(options)
    });
};

export const multipartRequestMutation = (options?: Partial<Options<MultipartRequestData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<MultipartRequestData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await multipartRequest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const complexParamsMutation = (options?: Partial<Options<ComplexParamsData>>): UseMutationOptions<{data: ComplexParamsResponse, response: Response, request: Request }, DefaultError, Options<ComplexParamsData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await complexParams({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const callWithResultFromHeaderMutation = (options?: Partial<Options<CallWithResultFromHeaderData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<CallWithResultFromHeaderData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await callWithResultFromHeader({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const testErrorCodeMutation = (options?: Partial<Options<TestErrorCodeData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<TestErrorCodeData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await testErrorCode({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

export const nonAsciiæøåÆøÅöôêÊ字符串Mutation = (options?: Partial<Options<NonAsciiæøåÆøÅöôêÊ字符串Data>>): UseMutationOptions<{data: NonAsciiæøåÆøÅöôêÊ字符串Response, response: Response, request: Request }, DefaultError, Options<NonAsciiæøåÆøÅöôêÊ字符串Data>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await nonAsciiæøåÆøÅöôêÊ字符串({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};

/**
 * Login User
 */
export const putWithFormUrlEncodedMutation = (options?: Partial<Options<PutWithFormUrlEncodedData>>): UseMutationOptions<{data: unknown, response: Response, request: Request }, DefaultError, Options<PutWithFormUrlEncodedData>> => {
    return {
        mutationFn: async (fnOptions) => {
            return await putWithFormUrlEncoded({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
        }
    };
};
