// This file is auto-generated by @hey-api/openapi-ts

export type FooRead = BarRead & {
    readonly foo?: string;
};

export type FooWrite = BarWrite & {
    foo?: string;
};

export type BarRead = Baz | {
    readonly bar?: string;
};

export type BarWrite = Baz | {
    bar?: string;
};

export type Baz = {
    baz?: string;
};

export type QuxAllRead = {
    readonly baz?: string;
};

export type Quux = {
    baz?: Array<Baz>;
    qux?: QuxAllRead;
};

export type ReadableFooReadWrite = BarRead;

export type WritableFooReadWrite = BarRead & {
    foo?: string;
};

export type ReadableCorge = {
    bar?: {
        readonly baz?: boolean;
    };
};

export type WritableCorge = {
    foo?: {
        baz?: boolean;
    };
};

export type PostFooReadWriteData = {
    body: WritableFooReadWrite;
    path?: never;
    query?: never;
    url: '/foo-read-write';
};

export type PostFooReadWriteResponses = {
    /**
     * OK
     */
    200: ReadableFooReadWrite;
};

export type PostFooReadWriteResponse = PostFooReadWriteResponses[keyof PostFooReadWriteResponses];

export type PostFooReadData = {
    body: FooRead;
    path?: never;
    query?: never;
    url: '/foo-read';
};

export type PostFooReadResponses = {
    /**
     * OK
     */
    200: FooRead;
};

export type PostFooReadResponse = PostFooReadResponses[keyof PostFooReadResponses];

export type PostFooWriteData = {
    body: FooWrite;
    path?: never;
    query?: never;
    url: '/foo-write';
};

export type PostFooWriteResponses = {
    /**
     * OK
     */
    200: FooWrite;
};

export type PostFooWriteResponse = PostFooWriteResponses[keyof PostFooWriteResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};