export const identifiers = {
  /**
   * {@link https://valibot.dev/api/#actions Actions}
   */
  actions: {
    args: 'args',
    base64: 'base64',
    bic: 'bic',
    brand: 'brand',
    bytes: 'bytes',
    check: 'check',
    checkItems: 'checkItems',
    creditCard: 'creditCard',
    cuid2: 'cuid2',
    decimal: 'decimal',
    description: 'description',
    digits: 'digits',
    email: 'email',
    emoji: 'emoji',
    empty: 'empty',
    endsWith: 'endsWith',
    entries: 'entries',
    everyItem: 'everyItem',
    excludes: 'excludes',
    filterItems: 'filterItems',
    findItem: 'findItem',
    finite: 'finite',
    flavor: 'flavor',
    graphemes: 'graphemes',
    gtValue: 'gtValue',
    hash: 'hash',
    hexColor: 'hexColor',
    hexadecimal: 'hexadecimal',
    imei: 'imei',
    includes: 'includes',
    integer: 'integer',
    ip: 'ip',
    ipv4: 'ipv4',
    ipv6: 'ipv6',
    isoDate: 'isoDate',
    isoDateTime: 'isoDateTime',
    isoTime: 'isoTime',
    isoTimeSecond: 'isoTimeSecond',
    isoTimestamp: 'isoTimestamp',
    isoWeek: 'isoWeek',
    length: 'length',
    ltValue: 'ltValue',
    mac: 'mac',
    mac48: 'mac48',
    mac64: 'mac64',
    mapItems: 'mapItems',
    maxBytes: 'maxBytes',
    maxEntries: 'maxEntries',
    maxGraphemes: 'maxGraphemes',
    maxLength: 'maxLength',
    maxSize: 'maxSize',
    maxValue: 'maxValue',
    maxWords: 'maxWords',
    metadata: 'metadata',
    mimeType: 'mimeType',
    minBytes: 'minBytes',
    minEntries: 'minEntries',
    minGraphemes: 'minGraphemes',
    minLength: 'minLength',
    minSize: 'minSize',
    minValue: 'minValue',
    minWords: 'minWords',
    multipleOf: 'multipleOf',
    nanoid: 'nanoid',
    nonEmpty: 'nonEmpty',
    normalize: 'normalize',
    notBytes: 'notBytes',
    notEntries: 'notEntries',
    notGraphemes: 'notGraphemes',
    notLength: 'notLength',
    notSize: 'notSize',
    notValue: 'notValue',
    notValues: 'notValues',
    notWords: 'notWords',
    octal: 'octal',
    parseJson: 'parseJson',
    partialCheck: 'partialCheck',
    rawCheck: 'rawCheck',
    rawTransform: 'rawTransform',
    readonly: 'readonly',
    reduceItems: 'reduceItems',
    regex: 'regex',
    returns: 'returns',
    rfcEmail: 'rfcEmail',
    safeInteger: 'safeInteger',
    size: 'size',
    slug: 'slug',
    someItem: 'someItem',
    sortItems: 'sortItems',
    startsWith: 'startsWith',
    stringifyJson: 'stringifyJson',
    title: 'title',
    toLowerCase: 'toLowerCase',
    toMaxValue: 'toMaxValue',
    toMinValue: 'toMinValue',
    toUpperCase: 'toUpperCase',
    transform: 'transform',
    trim: 'trim',
    trimEnd: 'trimEnd',
    trimStart: 'trimStart',
    ulid: 'ulid',
    url: 'url',
    uuid: 'uuid',
    value: 'value',
    values: 'values',
    words: 'words',
  },
  /**
   * {@link https://valibot.dev/api/#async Async}
   */
  async: {
    argsAsync: 'argsAsync',
    arrayAsync: 'arrayAsync',
    awaitAsync: 'awaitAsync',
    checkAsync: 'checkAsync',
    checkItemsAsync: 'checkItemsAsync',
    customAsync: 'customAsync',
    exactOptionalAsync: 'exactOptionalAsync',
    fallbackAsync: 'fallbackAsync',
    forwardAsync: 'forwardAsync',
    getDefaultsAsync: 'getDefaultsAsync',
    getFallbacksAsync: 'getFallbacksAsync',
    intersectAsync: 'intersectAsync',
    lazyAsync: 'lazyAsync',
    looseObjectAsync: 'looseObjectAsync',
    looseTupleAsync: 'looseTupleAsync',
    mapAsync: 'mapAsync',
    nonNullableAsync: 'nonNullableAsync',
    nonNullishAsync: 'nonNullishAsync',
    nonOptionalAsync: 'nonOptionalAsync',
    nullableAsync: 'nullableAsync',
    nullishAsync: 'nullishAsync',
    objectAsync: 'objectAsync',
    objectWithRestAsync: 'objectWithRestAsync',
    optionalAsync: 'optionalAsync',
    parseAsync: 'parseAsync',
    parserAsync: 'parserAsync',
    partialAsync: 'partialAsync',
    partialCheckAsync: 'partialCheckAsync',
    pipeAsync: 'pipeAsync',
    rawCheckAsync: 'rawCheckAsync',
    rawTransformAsync: 'rawTransformAsync',
    recordAsync: 'recordAsync',
    requiredAsync: 'requiredAsync',
    returnsAsync: 'returnsAsync',
    safeParseAsync: 'safeParseAsync',
    safeParserAsync: 'safeParserAsync',
    setAsync: 'setAsync',
    strictObjectAsync: 'strictObjectAsync',
    strictTupleAsync: 'strictTupleAsync',
    transformAsync: 'transformAsync',
    tupleAsync: 'tupleAsync',
    tupleWithRestAsync: 'tupleWithRestAsync',
    undefinedableAsync: 'undefinedableAsync',
    unionAsync: 'unionAsync',
    variantAsync: 'variantAsync',
  },
  /**
   * {@link https://valibot.dev/api/#methods Methods}
   */
  methods: {
    assert: 'assert',
    config: 'config',
    fallback: 'fallback',
    flatten: 'flatten',
    forward: 'forward',
    getDefault: 'getDefault',
    getDefaults: 'getDefaults',
    getDescription: 'getDescription',
    getFallback: 'getFallback',
    getFallbacks: 'getFallbacks',
    getMetadata: 'getMetadata',
    getTitle: 'getTitle',
    is: 'is',
    keyof: 'keyof',
    message: 'message',
    omit: 'omit',
    parse: 'parse',
    parser: 'parser',
    partial: 'partial',
    pick: 'pick',
    pipe: 'pipe',
    required: 'required',
    safeParse: 'safeParse',
    safeParser: 'safeParser',
    summarize: 'summarize',
    unwrap: 'unwrap',
  },
  /**
   * {@link https://valibot.dev/api/#schemas Schemas}
   */
  schemas: {
    any: 'any',
    array: 'array',
    bigInt: 'bigint',
    blob: 'blob',
    boolean: 'boolean',
    custom: 'custom',
    date: 'date',
    enum: 'enum',
    exactOptional: 'exactOptional',
    file: 'file',
    function: 'function',
    instance: 'instance',
    intersect: 'intersect',
    lazy: 'lazy',
    literal: 'literal',
    looseObject: 'looseObject',
    looseTuple: 'looseTuple',
    map: 'map',
    nan: 'nan',
    never: 'never',
    nonNullable: 'nonNullable',
    nonNullish: 'nonNullish',
    nonOptional: 'nonOptional',
    null: 'null',
    nullable: 'nullable',
    nullish: 'nullish',
    number: 'number',
    object: 'object',
    objectWithRest: 'objectWithRest',
    optional: 'optional',
    picklist: 'picklist',
    promise: 'promise',
    record: 'record',
    set: 'set',
    strictObject: 'strictObject',
    strictTuple: 'strictTuple',
    string: 'string',
    symbol: 'symbol',
    tuple: 'tuple',
    tupleWithRest: 'tupleWithRest',
    undefined: 'undefined',
    undefinedable: 'undefinedable',
    union: 'union',
    unknown: 'unknown',
    variant: 'variant',
    void: 'void',
  },
  /**
   * {@link https://valibot.dev/api/#storages Storages}
   */
  storages: {
    // TODO: implement if necessary
  },
  /**
   * {@link https://valibot.dev/api/#types Types}
   */
  types: {
    // TODO: implement if necessary
    GenericSchema: 'GenericSchema',
  },
  /**
   * {@link https://valibot.dev/api/#utils Utils}
   */
  utils: {
    // TODO: implement if necessary
  },
};
