// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Foo = {
    foo: string;
    [key: string]: any;
};

export type Bar = Foo & {
    [key: string]: any;
};

export type Baz = Foo & {
    bar: string;
    [key: string]: any;
};

export type Qux = {
    [key: string]: any;
};
