openapi: 3.0.2
info:
  title: OpenAPI 3.0.2 case example
  version: '1'
paths:
  /foo:
    get:
      parameters:
        - description: 'original name: fooBar'
          in: query
          name: fooBar
          required: true
          schema:
            type: string
        - description: 'original name: BarBaz'
          in: query
          name: BarBaz
          required: true
          schema:
            type: string
        - description: 'original name: qux_quux'
          in: query
          name: qux_quux
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/201'
components:
  schemas:
    '201':
      description: 'original name: 201'
      type: number
    Foo:
      description: 'original name: Foo'
      properties:
        fooBar:
          description: 'original name: fooBar'
          allOf:
            - $ref: '#/components/schemas/foo_bar'
        BarBaz:
          description: 'original name: BarBaz'
          allOf:
            - $ref: '#/components/schemas/Foo'
        qux_quux:
          description: 'original name: qux_quux'
          properties:
            fooBar:
              description: 'original name: fooBar'
              allOf:
                - $ref: '#/components/schemas/fooBar'
            BarBaz:
              description: 'original name: BarBaz'
              allOf:
                - $ref: '#/components/schemas/FooBar'
            qux_quux:
              description: 'original name: qux_quux'
              type: boolean
          required:
            - fooBar
            - BarBaz
            - qux_quux
          type: object
      required:
        - fooBar
        - BarBaz
        - qux_quux
      type: object
    foo_bar:
      description: 'original name: foo_bar'
      type: boolean
    fooBar:
      description: 'original name: fooBar'
      type: number
    FooBar:
      description: 'original name: FooBar'
      type: string
