openapi: 3.0.3
info:
  title: OpenAPI 3.0 sdk nested classes example
  version: 1.0.0
  description: Test schema for nested class generation with various operationId patterns
servers:
  - url: https://api.example.com/v1
paths:
  /v1/tenants/providers/domains:
    get:
      tags:
        - v1
        - tenants
        - providers
        - domains
      operationId: v1.tenants.providers.domains.get
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - v1
        - tenants
        - providers
        - domains
      operationId: v1.tenants.providers.domains.post
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /v2/tenants/providers/domains:
    get:
      tags:
        - v2
        - tenants
        - providers
        - domains
      operationId: v2.tenants.providers.domains.get
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - v2
        - tenants
        - providers
        - domains
      operationId: v2.tenants.providers.domains.post
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
