// This file is auto-generated by @hey-api/openapi-ts

import { Injectable } from '@nestjs/common';

import type { AxiosResponse } from 'axios';

import { AdvancedApiClient } from '../advancedapi-client.service.gen';

import type { Options, TDataShape } from '../types.gen';

import type { PostApiVbyApiVersionRequestBodyData } from '../../types.gen';

@Injectable()
export class AdvancedApiRequestBodyService {
    constructor(private readonly client: AdvancedApiClient) {
    }
    public async postApiVApiVersionRequestBody(options: PostApiVbyApiVersionRequestBodyData): Promise<AxiosResponse<unknown>> {
        return await this.client.post(options.url, 'body' in options ? options.body : undefined, {
            ...options
        });
    }
}