// This file is auto-generated by @hey-api/openapi-ts

export type type = 'foo' | 'bar';

export const type = {
    FOO: 'foo',
    BAR: 'bar'
} as const;

export type Foo = {
    type?: 'foo' | 'bar';
};