export const identifiers = {
  Dict: 'Dict',
  Field: 'Field',
  List: 'List',
  Literal: 'Literal',
  Optional: 'Optional',
  Union: 'Union',
  alias: 'alias',
  default: 'default',
  description: 'description',
  ge: 'ge',
  gt: 'gt',
  le: 'le',
  lt: 'lt',
  max_length: 'max_length',
  min_length: 'min_length',
  model_config: 'model_config',
  multiple_of: 'multiple_of',
  pattern: 'pattern',
};
