// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zFoo = z.object({
    foo: z.optional(z.literal('foo')),
    bar: z.optional(z.literal(3.2)),
    baz: z.optional(z.literal(-1)),
    qux: z.optional(z.literal(true)),
    quux: z.optional(z.tuple([
        z.literal(1),
        z.literal(2),
        z.literal(3),
        z.literal('foo'),
        z.literal(true)
    ])),
    corge: z.optional(z.object({})),
    garply: z.optional(z.coerce.bigint())
});