// This file is auto-generated by @hey-api/openapi-ts

import type { GetFooResponse } from './types.gen';

const fooSchemaResponseTransformer = (data: any) => {
    if (data.foo) {
        data.foo = new Date(data.foo);
    }
    if (data.bar) {
        data.bar = new Date(data.bar);
    }
    if (data.requiredBaz) {
        data.requiredBaz = new Date(data.requiredBaz);
    }
    return data;
};

export const getFooResponseTransformer = async (data: any): Promise<GetFooResponse> => {
    data = data.map((item: any) => {
        return fooSchemaResponseTransformer(item);
    });
    return data;
};