// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TextEntry = {
    type: 'text';
    content: string;
    createdAt: Date;
    updatedAt?: Date;
};

export type FileEntry = {
    type: 'file';
    fileId: string;
    fileName: string;
    createdAt: Date;
    fileSize?: bigint;
};

export type ImageEntry = {
    type: 'image';
    imageUrl: string;
    width?: number;
    height?: number;
    capturedAt: Date;
};

export type Entry = ({
    type: 'text';
} & TextEntry) | ({
    type: 'file';
} & FileEntry) | ({
    type: 'image';
} & ImageEntry);

export type Container = {
    id: string;
    entry: Entry;
    createdAt: Date;
    entries?: Array<Entry>;
};

export type EmailEvent = {
    kind: 'email';
    emailDetails: {
        subject: string;
        sentAt: Date;
        receivedAt?: Date;
    };
    timestamp: Date;
};

export type PushEvent = {
    kind: 'push';
    pushDetails: {
        title: string;
        deliveredAt: Date;
        expiresAt?: Date;
    };
    timestamp: Date;
};

export type SmsEvent = {
    kind: 'sms';
    smsDetails: {
        phoneNumber: string;
        sentAt: Date;
    };
    timestamp: Date;
};

export type Event = ({
    kind: 'email';
} & EmailEvent) | ({
    kind: 'push';
} & PushEvent) | ({
    kind: 'sms';
} & SmsEvent);

export type InfoNotification = {
    level: 'info';
    message: string;
    createdAt: Date;
};

export type WarningNotification = {
    level: 'warning';
    message: string;
    severity?: number;
    createdAt: Date;
};

export type ErrorNotification = {
    level: 'error';
    message: string;
    errorCode: string;
    occurredAt: Date;
    resolvedAt?: Date;
};

export type Notification = ({
    level?: 'info';
} & InfoNotification) | ({
    level?: 'warning';
} & WarningNotification) | ({
    level?: 'error';
} & ErrorNotification);

export type LoginActivity = {
    action: 'login';
    ipAddress: string;
    loginTime: Date;
    lastSeenAt?: Date;
};

export type LogoutActivity = {
    action: 'logout';
    reason?: string;
    logoutTime: Date;
    sessionDuration?: bigint;
};

export type PasswordChangeActivity = {
    action: 'password_change';
    changedAt: Date;
    expiresAt?: Date;
};

export type Activity = ({
    action: 'login';
} & LoginActivity) | ({
    action: 'logout';
} & LogoutActivity) | ({
    action: 'password_change';
} & PasswordChangeActivity);

export type GetEntriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entries';
};

export type GetEntriesResponses = {
    /**
     * OK
     */
    200: Array<Entry>;
};

export type GetEntriesResponse = GetEntriesResponses[keyof GetEntriesResponses];

export type GetEntryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entry';
};

export type GetEntryResponses = {
    /**
     * OK
     */
    200: Entry;
};

export type GetEntryResponse = GetEntryResponses[keyof GetEntryResponses];

export type GetNestedEntryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nested-entry';
};

export type GetNestedEntryResponses = {
    /**
     * OK
     */
    200: Container;
};

export type GetNestedEntryResponse = GetNestedEntryResponses[keyof GetNestedEntryResponses];

export type GetEventData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/event';
};

export type GetEventResponses = {
    /**
     * OK
     */
    200: Event;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type GetNotificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notification';
};

export type GetNotificationResponses = {
    /**
     * OK
     */
    200: Notification;
};

export type GetNotificationResponse = GetNotificationResponses[keyof GetNotificationResponses];

export type GetActivityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/activity';
};

export type GetActivityResponses = {
    /**
     * OK
     */
    200: Activity;
};

export type GetActivityResponse = GetActivityResponses[keyof GetActivityResponses];
