// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zBar = z.object({
    foo: z.optional(z.enum(['one', 'two']))
});

export const zBaz = z.object({
    foo: z.optional(z.enum(['three']))
});

export const zSpæcial = z.object({
    foo: z.optional(z.enum(['four']))
});

export const zFoo = z.discriminatedUnion('foo', [
    z.extend(zBar, { foo: z.enum(['one', 'two']) }),
    z.extend(zBaz, { foo: z.literal('three') }),
    z.extend(zSpæcial, { foo: z.literal('four') })
]);
