// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/v4';

export const zBaz = z.string().regex(/foo\nbar/).readonly().default('baz');

export const zQux = z.record(z.string(), z.object({
    qux: z.string().optional()
}));

/**
 * This is Foo schema.
 */
export const zFoo = z.object({
    foo: z.string().regex(/^\d{3}-\d{2}-\d{4}$/).optional(),
    bar: z.lazy((): any => zBar).optional(),
    baz: z.array(z.lazy((): any => zFoo)).optional(),
    qux: z.int().gt(0).default(0).optional()
}).nullable().default(null);

/**
 * This is Bar schema.
 */
export const zBar = z.object({
    foo: zFoo.optional()
});

/**
 * This is Foo parameter.
 */
export const zFoo2 = z.string();

export const zFoo3 = z.object({
    foo: zBar.optional()
});

export const zPatchFooBody = z.object({
    foo: z.string().optional()
});

export const zPatchFooQuery = z.object({
    foo: z.string().optional(),
    bar: zBar.optional(),
    baz: z.object({
        baz: z.string().optional()
    }).optional(),
    qux: z.iso.date().optional(),
    quux: z.iso.datetime({ offset: true }).optional()
});

export const zPostFooBody = zFoo3;
