// This file is auto-generated by @hey-api/openapi-ts

export type Foo = {
    type?: Type;
};

export enum Type {
    FOO = 'foo',
    BAR = 'bar'
}

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};