// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type BooleanOneOf = ({
    use_custom: false;
} & AutoConfig) | ({
    use_custom: true;
} & CustomConfig);

export type AutoConfig = {
    use_custom: false;
    auto_setting: string;
};

export type CustomConfig = {
    use_custom: true;
    custom_value: number;
};

export type BooleanAnyOf = ({
    use_custom?: false;
} & AutoConfig) | ({
    use_custom?: true;
} & CustomConfig);

export type IntegerOneOf = ({
    type_id: 1;
} & TypeOne) | ({
    type_id: 2;
} & TypeTwo);

export type TypeOne = {
    type_id: 1;
    one_data: string;
};

export type TypeTwo = {
    type_id: 2;
    two_data: string;
};

export type NumberOneOf = ({
    version: 1;
} & VersionAlpha) | ({
    version: 2.5;
} & VersionBeta);

export type VersionAlpha = {
    version: 1;
    alpha_field: string;
};

export type VersionBeta = {
    version: 2.5;
    beta_field: string;
};

export type IntegerAllOfBase = {
    kind: number;
};

export type IntegerAllOfChildA = Omit<IntegerAllOfBase, 'kind'> & {
    child_a_field: string;
    kind: 1;
};

export type IntegerAllOfChildB = Omit<IntegerAllOfBase, 'kind'> & {
    child_b_field: string;
    kind: 2;
};

export type NullableIntegerOneOf = ({
    tag: 10;
} & NullableVariantX) | ({
    tag: 20;
} & NullableVariantY);

export type NullableVariantX = {
    tag: 10 | null;
    x_data: string;
};

export type NullableVariantY = {
    tag: 20 | null;
    y_data: string;
};
