// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBar = z.union([
    z.object({
        bar: z.string()
    }),
    z.object({
        baz: z.string()
    })
]);

export const zFoo = zBar.and(z.object({
    foo: z.string()
}));