name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    if: github.repository == 'hey-api/hey-api'
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.GIT_APP_CLIENT_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Run update contributors script
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: scripts/update-contributors.sh

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 'chore: update contributors list'
          file_pattern: CONTRIBUTORS.md
