// This file is auto-generated by @hey-api/openapi-ts

export type { ClientOptions, CommentV152Comment, GetUsersData, GetUsersResponse, GetUsersResponses, PostPostsData, PostPostsResponse, PostPostsResponses, PostV213Post, UserProfileV100UserProfile, UserV100User } from './types.gen';
